/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteRouteImport } from './routes/_tabs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as TabsProjectsRouteImport } from './routes/_tabs/projects'
import { Route as TabsMeRouteImport } from './routes/_tabs/me'
import { Route as TabsMaterialsRouteImport } from './routes/_tabs/materials'

const TabsRouteRoute = TabsRouteRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsProjectsRoute = TabsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsMeRoute = TabsMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsMaterialsRoute = TabsMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => TabsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/materials': typeof TabsMaterialsRoute
  '/me': typeof TabsMeRoute
  '/projects': typeof TabsProjectsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/materials': typeof TabsMaterialsRoute
  '/me': typeof TabsMeRoute
  '/projects': typeof TabsProjectsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteRouteWithChildren
  '/_tabs/materials': typeof TabsMaterialsRoute
  '/_tabs/me': typeof TabsMeRoute
  '/_tabs/projects': typeof TabsProjectsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/materials'
    | '/me'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/materials'
    | '/me'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/_tabs/materials'
    | '/_tabs/me'
    | '/_tabs/projects'
    | '/projects/$projectId'
    | '/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRouteRoute: typeof TabsRouteRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/projects': {
      id: '/_tabs/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof TabsProjectsRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/me': {
      id: '/_tabs/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof TabsMeRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/materials': {
      id: '/_tabs/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof TabsMaterialsRouteImport
      parentRoute: typeof TabsRouteRoute
    }
  }
}

interface TabsRouteRouteChildren {
  TabsMaterialsRoute: typeof TabsMaterialsRoute
  TabsMeRoute: typeof TabsMeRoute
  TabsProjectsRoute: typeof TabsProjectsRoute
}

const TabsRouteRouteChildren: TabsRouteRouteChildren = {
  TabsMaterialsRoute: TabsMaterialsRoute,
  TabsMeRoute: TabsMeRoute,
  TabsProjectsRoute: TabsProjectsRoute,
}

const TabsRouteRouteWithChildren = TabsRouteRoute._addFileChildren(
  TabsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRouteRoute: TabsRouteRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
