/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabsRouteRouteImport } from './routes/_tabs/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as TabsSettingsRouteImport } from './routes/_tabs/settings'
import { Route as TabsProjectsRouteImport } from './routes/_tabs/projects'
import { Route as TabsDiscoverRouteImport } from './routes/_tabs/discover'

const TabsRouteRoute = TabsRouteRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsSettingsRoute = TabsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsProjectsRoute = TabsProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => TabsRouteRoute,
} as any)
const TabsDiscoverRoute = TabsDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => TabsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof TabsDiscoverRoute
  '/projects': typeof TabsProjectsRoute
  '/settings': typeof TabsSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof TabsDiscoverRoute
  '/projects': typeof TabsProjectsRoute
  '/settings': typeof TabsSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_tabs': typeof TabsRouteRouteWithChildren
  '/_tabs/discover': typeof TabsDiscoverRoute
  '/_tabs/projects': typeof TabsProjectsRoute
  '/_tabs/settings': typeof TabsSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/new': typeof ProjectsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/projects'
    | '/settings'
    | '/projects/$projectId'
    | '/projects/new'
  id:
    | '__root__'
    | '/'
    | '/_tabs'
    | '/_tabs/discover'
    | '/_tabs/projects'
    | '/_tabs/settings'
    | '/projects/$projectId'
    | '/projects/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TabsRouteRoute: typeof TabsRouteRouteWithChildren
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tabs': {
      id: '/_tabs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tabs/settings': {
      id: '/_tabs/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof TabsSettingsRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/projects': {
      id: '/_tabs/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof TabsProjectsRouteImport
      parentRoute: typeof TabsRouteRoute
    }
    '/_tabs/discover': {
      id: '/_tabs/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof TabsDiscoverRouteImport
      parentRoute: typeof TabsRouteRoute
    }
  }
}

interface TabsRouteRouteChildren {
  TabsDiscoverRoute: typeof TabsDiscoverRoute
  TabsProjectsRoute: typeof TabsProjectsRoute
  TabsSettingsRoute: typeof TabsSettingsRoute
}

const TabsRouteRouteChildren: TabsRouteRouteChildren = {
  TabsDiscoverRoute: TabsDiscoverRoute,
  TabsProjectsRoute: TabsProjectsRoute,
  TabsSettingsRoute: TabsSettingsRoute,
}

const TabsRouteRouteWithChildren = TabsRouteRoute._addFileChildren(
  TabsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TabsRouteRoute: TabsRouteRouteWithChildren,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
